<a href="https://colab.research.google.com/github/majorquev/DBDC_202106_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Jorge Arévalo Labarca <br>
**E-mail ayudante:** jorge.arevalol@usach.cl



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una maztriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [3]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos

M1 <- matrix(c(10,30,40,100,600,59), ncol = 3, nrow = 2 )
M1

[,1] [,2] [,3]
[1,] 10    40  600 
[2,] 30   100   59

In [4]:
M1 <- matrix(c(10,30,40,100,600,59), ncol = 3, nrow = 2, byrow = TRUE)
M1

[,1] [,2] [,3]
[1,]  10   30  40  
[2,] 100  600  59

In [6]:
# clase y atributo dim
class(M1)
typeof(M1)

[1] "matrix" "array"

[1] "double"

In [8]:
# Genere dos vectores del mismo largo y forme una matriz.
v1 <- c(8,7,6,5)
v2 <- c(1,1,2,3)
v3 <- c(0,1,0,1)


In [9]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

M2 <- cbind(v1,v2,v3) # Dispone los vectores como columnas
M2


v1 v2 v3
[1,] 8  1  0 
[2,] 7  1  1 
[3,] 6  2  0 
[4,] 5  3  1

In [10]:
M3 <- rbind(v1,v2,v3) # Dispone los vectores como filas.
M3


[,1] [,2] [,3] [,4]
v1 8    7    6    5   
v2 1    1    2    3   
v3 0    1    0    1

In [15]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
v4 <- c(100,200,300)
rbind(v1,v4)



Warning message in rbind(v1, v4):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3] [,4]
v1   8    7    6    5 
v4 100  200  300  100

In [12]:
# función diag para la definición de matrices diagonales
#?diag 

diag(c(1,2,3,4,5))



[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [16]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
M2
# quiero rescatar el elemento "(2,1)", de M2

M2[2,1]

# CUIDADO:No es lo mismo que 
M2[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

v1 v2 v3
[1,] 8  1  0 
[2,] 7  1  1 
[3,] 6  2  0 
[4,] 5  3  1

v1 
 7

[1] 7 8

In [18]:
# Para acceder a una fila completa
M2[2,]


# Para acceder a una columna completa
M2[,3]


v1 v2 v3 
 7  1  1

[1] 0 1 0 1

In [19]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 1 por un 99 (el 1 de la pos 2,2)
M2[2,2] <- 99 

In [20]:
M2

v1 v2 v3
[1,] 8   1 0 
[2,] 7  99 1 
[3,] 6   2 0 
[4,] 5   3 1

In [22]:
# Nombres de columnas
colnames(M2)
# Nomrbes de las filas
rownames(M2)

[1] "v1" "v2" "v3"

NULL

In [23]:
rownames(M2) <- c("fila1" , "fila2", "fila3", "fila4")

In [24]:
M2

v1 v2 v3
fila1 8   1 0 
fila2 7  99 1 
fila3 6   2 0 
fila4 5   3 1

In [25]:
# Acceso mediante nombres
M2["fila2","v1"]

[1] 7

In [28]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (2,3) de M2
# 1: Crear una matriz de 4x3 con TRUE en dichas posiciones y FALSE en las restantes.


indices <- matrix(c(T,F,F,F, F,F,F,F  ,F,T,F,F),
                  nrow = 4, 
                  ncol = 3,
                  byrow = FALSE)
indices 

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE

In [29]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M2[indices]

[1] 8 1

In [30]:
# Podríamos consultar los casos en que los valores de M2 son enores o iguales a 4
M2 <= 4

v1    v2    v3  
fila1 FALSE  TRUE TRUE
fila2 FALSE FALSE TRUE
fila3 FALSE  TRUE TRUE
fila4 FALSE  TRUE TRUE

In [31]:
M2[M2 <= 4]

[1] 1 2 3 0 1 0 1

In [33]:
M2

v1 v2 v3
fila1 8   1 0 
fila2 1  99 1 
fila3 6   2 0 
fila4 5   3 1

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [37]:
# transponer una matriz
M2
t(M2)

v1 v2 v3
fila1 8   1 0 
fila2 1  99 1 
fila3 6   2 0 
fila4 5   3 1

fila1 fila2 fila3 fila4
v1 8      1    6     5    
v2 1     99    2     3    
v3 0      1    0     1

In [38]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices

M3 %*% M2

v1  v2  v3
v1 132 728 12
v2  36 113  4
v3   6 102  2

In [39]:
# Multiplicación de matrices
M2 * M3 # multiplicación componente a componente


ERROR: ignored

In [40]:
M2 * M2

v1 v2   v3
fila1 64    1 0 
fila2  1 9801 1 
fila3 36    4 0 
fila4 25    9 1

In [41]:
# podemos calcular determinantes
# ?det

M <- M3 %*% M2


In [42]:
det(M)

[1] -23040

In [43]:
# Podemos invertir matrices
# ?solve
solve(M)

v1           v2           v3          
v1  0.007899306  0.010069444 -0.067534722
v2  0.002083333 -0.008333333  0.004166667
v3 -0.129947917  0.394791667  0.490104167